plugins { id 'com.android.application' }

android { namespace 'br.com.folio'; compileSdk 35
    defaultConfig {
        applicationId 'br.com.folio'
        minSdk 26
        targetSdk 35
        versionCode 11
        versionName '2.00'
        ndk { abiFilters 'armeabi-v7a', 'arm64-v8a' }
    }
}

dependencies {
    implementation 'com.tom-roush:pdfbox-android:2.0.27.0'
    implementation 'org.apache.commons:commons-compress:1.26.2'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.9.24'
    implementation files('libs/sherpa-onnx-1.13.6.aar')
}
